//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatCode_Selenium.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dev.azure.com/DMCHosting-Auvenir-Org/_usersSettings/tokens")]
        public string PAT {
            get {
                return ((string)(this["PAT"]));
            }
            set {
                this["PAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"contributionIds\":[\"ms.vss-work-web.work-item-query-data-provider\"],\"context\":{\"" +
            "properties\":{\"wiql\":\"SELECT [System.Id], [System.WorkItemType], [System.Title], " +
            "[Microsoft.VSTS.Scheduling.DueDate], [System.AssignedTo], [System.State], [Syste" +
            "m.Tags] FROM WorkItemLinks WHERE (Source.[System.TeamProject] = @project and Sou" +
            "rce.[System.WorkItemType] in (\'Bug\') and Source.[System.AreaPath] under \'Auvenir" +
            "App\\\\R6.2.1\' and Source.[System.State] = \'Queue\' and Source.[Custom.DefectPriori" +
            "ty] in (\'1. Blocker\', \'2. Acceptance\', \'3. Critical\', \'4. High\')) and ([System.L" +
            "inks.LinkType] = \'System.LinkTypes.Duplicate-Forward\') and (Target.[System.TeamP" +
            "roject] = @project) ORDER BY [System.Id] mode(Recursive)\",\"fields\":[\"System.Id;7" +
            "0\",\"System.WorkItemType;75\",\"System.Title;721\",\"Microsoft.VSTS.Scheduling.DueDat" +
            "e;120\",\"System.AssignedTo;282\",\"System.State;84\",\"System.Tags;200\"],\"sortFields\"" +
            ":[\"System.Id;asc\"],\"top\":null,\"persistenceId\":\"2d07fae6-d0cc-47c7-9de2-4c69cb6ee" +
            "92a\",\"isDirty\":false,\"pageSource\":{\"contributionPaths\":[\"VSS\",\"VSS/Resources\",\"q" +
            "\",\"knockout\",\"mousetrap\",\"mustache\",\"react\",\"react-dom\",\"react-transition-group\"" +
            ",\"jQueryUI\",\"jquery\",\"OfficeFabric\",\"tslib\",\"@uifabric\",\"VSSUI\",\"TFSUI\",\"TFSUI/R" +
            "esources\",\"ContentRendering\",\"ContentRendering/Resources\",\"Charts\",\"Charts/Resou" +
            "rces\",\"WidgetComponents\",\"WidgetComponents/Resources\",\"TFS\",\"Notifications\",\"Pre" +
            "sentation/Scripts/marked\",\"Presentation/Scripts/URI\",\"Presentation/Scripts/punyc" +
            "ode\",\"Presentation/Scripts/IPv6\",\"Presentation/Scripts/SecondLevelDomains\",\"high" +
            "charts\",\"highcharts/highcharts-more\",\"highcharts/modules/accessibility\",\"highcha" +
            "rts/modules/heatmap\",\"highcharts/modules/funnel\",\"Analytics\"],\"diagnostics\":{\"se" +
            "ssionId\":\"ea781f00-e504-4626-b316-c8e44cf16d8f\",\"activityId\":\"ea781f00-e504-4626" +
            "-b316-c8e44cf16d8f\",\"bundlingEnabled\":true,\"cdnAvailable\":true,\"cdnEnabled\":true" +
            ",\"webPlatformVersion\":\"M226\",\"serviceVersion\":\"Dev19.M226.1 (build: AzureDevOps_" +
            "M226_20230901.2)\"},\"navigation\":{\"topMostLevel\":8,\"area\":\"\",\"currentController\":" +
            "\"Apps\",\"currentAction\":\"ContributedHub\",\"commandName\":\"ms.vss-work-web.query-rou" +
            "te\",\"routeId\":\"ms.vss-work-web.query-route\",\"routeTemplates\":[\"{project}/{team}/" +
            "_queries/{view}/{id}/{*parameters}\",\"{project}/_queries/{view}/{id}/{*parameters" +
            "}\",\"{project}/{team}/_workitems/{view}/{id}/{*parameters}\",\"{project}/_workitems" +
            "/{view}/{id}/{*parameters}\"],\"routeValues\":{\"project\":\"AuvenirApp\",\"view\":\"query" +
            "-edit\",\"id\":\"2d07fae6-d0cc-47c7-9de2-4c69cb6ee92a\",\"controller\":\"Apps\",\"action\":" +
            "\"ContributedHub\"}},\"project\":{\"id\":\"af906b5f-49aa-4d8e-8735-6661aab703a0\",\"name\"" +
            ":\"AuvenirApp\"},\"selectedHubGroupId\":\"ms.vss-work-web.work-hub-group\",\"selectedHu" +
            "bId\":\"ms.vss-work-web.query-hub\",\"url\":\"https://dev.azure.com/DMCHosting-Auvenir" +
            "-Org/AuvenirApp/_queries/query-edit/2d07fae6-d0cc-47c7-9de2-4c69cb6ee92a/\"},\"sou" +
            "rcePage\":{\"url\":\"https://dev.azure.com/DMCHosting-Auvenir-Org/AuvenirApp/_querie" +
            "s/query-edit/2d07fae6-d0cc-47c7-9de2-4c69cb6ee92a/\",\"routeId\":\"ms.vss-work-web.q" +
            "uery-route\",\"routeValues\":{\"project\":\"AuvenirApp\",\"view\":\"query-edit\",\"id\":\"2d07" +
            "fae6-d0cc-47c7-9de2-4c69cb6ee92a\",\"controller\":\"Apps\",\"action\":\"ContributedHub\"}" +
            "}}}}")]
        public string PayloadQuery {
            get {
                return ((string)(this["PayloadQuery"]));
            }
            set {
                this["PayloadQuery"] = value;
            }
        }
    }
}
